name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  BASE_URL: /website-next/

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Packages
        run: npm install
      - name: Build App
        run: npm run build:website
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Copy Static Files
        run: cp -r static/ build/website-next/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages # The branch the action should deploy to
          folder: build # The folder the action should deploy
