name: Deploy Website

on:
  push:
    branches:
      - main
      - next
      - "v*"
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
  # workflow_dispatch means to manual deploy production
  workflow_dispatch:
  # workflow_call means to deploy production from external workflow
  # it would be useful to trigger from fastify main repo instead of
  # daily schedule
  workflow_call:

permissions:
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BASE_URL: "/"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          check-latest: true
          node-version-file: ".nvmrc"

      - name: Enable corepack
        run: corepack enable

      - name: Install Packages
        run: npm ci --ignore-scripts

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Build website
        run: npm run build:website
        timeout-minutes: 30
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "./build"

  deploy-to-production:
    needs:
      - build-and-upload
    concurrency:
      group: ${{ github.ref_name }}-production
      cancel-in-progress: true
    env:
      BASE_URL: ""
    permissions:
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      deployment_url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
